models/product/options.yml
Reverts bigcommerce/theme-context-object-schemas#16
=> Revert "troubleshooting"

models/_root/product.yml
add a reference to options.yml
=> Modified models/_root/product.yml

models/_root/comparisons.yml
=> Modified models/_root/comparisons.yml

models/_root/order.yml
[DEVDOCS-3371](https://jira.bigcommerce.com/browse/DEVDOCS-3371)
order > comments should be a string
=> Modified models/_root/order.yml

models/_all.yml
=> Added models/_all.yml

.stoplight.json
=> Modified .stoplight.json

.stoplight.json, configuration/config.yml, toc.json
=> add config.json (config.yml), add to .stoplight.json and toc.json

toc.json
=> update toc to correct typo

models/_root/cart_id.yml
=> DEVDOCS-3498: relativize links

.github/CODEOWNERS, pull_request_template.md
* Add PR template, codeowner config
=> (no ticket): [meta] Add PR template, codeowner config

models/_root/category.yml, models/_root/comparisons.yml, models/_root/create_account.yml, models/_root/downloads.yml
=> Staging into main

theme-styles/_root/checkbox.md, theme-styles/_root/color.md, theme-styles/_root/font.md, theme-styles/_root/heading.md, theme-styles/_root/imageDimension.md, theme-styles/_root/optimizedCheckout-image.md, theme-styles/_root/reference.md, theme-styles/_root/select.md, theme-styles/_root/text.md
* add syntax meta to code blocks. very minor styling.
=> (no ticket): [revise] theme-styles/_root, add syntax meta

models/_root/urls.yml
=> (no ticket): [revise] urls.yml, fix typo

.eslintrc.json, .github/workflows/lint.yml, .gitignore, package-lock.json, package.json
* add npm script 
* add eslint config
* add GitHub action
cc @matthewvolk
=> (no ticket): [tools] MDX linter, create + add github action

README.md
* Updated README to reflect Stoplight migration
[DEVDOCS-4719]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-4719: [migrate] README, update links

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE/publication_pr_template.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, pull_request_template.md
=> (no ticket): [meta] GitHub, update codeowners + consolidate PR templates

models/_root/cart_id.yml, models/_root/checkout.yml
Provide a bulleted list in the present tense
* Update links to resolve in the current Dev Center
ping {names}
=> (no ticket): [update] cart_id + checkout models, update links

.github/workflows/deploy.yml
- [SELFDEV-216]
[SELFDEV-216]: https://bigcommercecloud.atlassian.net/browse/SELFDEV-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELFDEV-216: [dev] automate deploy on merge with main

models/_root/settings.yml
Added a definition for region _code
ping {names}
[DEVDOCS-5129]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-5129: [Update ] add region_code definition

models/_root/settings.yml
Fix site build error
ping {names}
=> fix file error

models/_root/page_type.yml
Added orderconfirmation
ping {names}
[DEVDOCS-5235]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-5235: [update] added orderconfirmation

models/_root/cart.yml
Fixed the items that did not expand and also updated other issues in the cart object.
ping {names}
[DEVDOCS-5340]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-5340: [update] update cart.yml file

models/_root/cart.yml
No ticket
Fixing alignment of properties under options
ping {names}
=> DEVDOCS-4868: [update] Cart.yml, align options properties

models/_root/product.yml
Adding shipping field
ping {names}
[DEVDOCS-5565]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-5565: [update] add shipping field

models/_root/product.yml
Fix display of the price field
ping {names}
[DEVDOCS-5565]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-5565: [revise] shipping field

models/_root/checkout.yml
Provide a bulleted list in the present tense
* Replace links
ping @becomevocal @bc-stephen-hilliard @bc-traciporter @bc-andreadao
[SELFDEV-370]: https://bigcommercecloud.atlassian.net/browse/SELFDEV-370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELFDEV-370: [update] Replace links
